game.sprites.background.init = function() {
    this.width = mge.game.width
    this.height = mge.game.height
    this.x = mge.game.width / 2
    this.y = mge.game.height / 2
    // Config
    this.maxLength  = 50
    this.lineWidth = 2
    this.isVisible = true
    // Create 2D paths
    this.initL1()
}

////////////////////////////////////////////////////////////////////////
// RENDER functions
////////////////////////////////////////////////////////////////////////
game.sprites.background.drawPiece = function (ctx, _path, h, s, l, _lineWidth, _affinity) {
    // Get the progress of the timer of the affinity
    let _timerProgress = game.timers[_affinity].progress
    // Level is not finished
    if (game.timers.levelCompleted.progress == 0 ||game.timers.levelCompleted.progress == 1) {
        // Calculate color depending of timer progress
        if (_timerProgress == 0) {
            // grey
            ctx.fillStyle = game.tools.hsla(0,0,95,100)
            ctx.strokeStyle = game.tools.hsla(0,0,85,100)
        } else if ((_timerProgress <= 0.2)) {
            ctx.fillStyle = game.tools.hsla(0,0,Math.min(100,80 + 200*_timerProgress),100)
            ctx.strokeStyle = game.tools.hsla(0,0,100,100)
        } else if ((_timerProgress <= 1)) {
            ctx.fillStyle = game.tools.hsla(h,s*_timerProgress,l+(100-l)*(1-_timerProgress),100)
            ctx.strokeStyle = game.tools.hsla(0,0,75,100)
        }
    } else {
        // Level is finished
        if (game.timers.levelCompleted.progress < 0.1) {
            ctx.fillStyle = game.tools.hsla(0,0,Math.min(100,80 + 200*_timerProgress),100)
            ctx.strokeStyle = game.tools.hsla(0,0,90,100)
        } else if (game.timers.levelCompleted.progress < 0.5 ) {
            ctx.fillStyle = game.tools.hsla(h,(s+10)*_timerProgress,l+(100-l)*(1-_timerProgress),100)
            ctx.strokeStyle = game.tools.hsla(0,0,50,100)
        } else {
            ctx.fillStyle = game.tools.hsla(h,s+10,l-5+(game.timers.levelCompleted.progress-0.5)*70,100)
            ctx.strokeStyle = game.tools.hsla(0,0,50+(game.timers.levelCompleted.progress-0.5)*150,100)
        }
    }
    // Draw
    ctx.lineWidth = _lineWidth
    ctx.lineJoin = 'round'
    ctx.fill(_path)
    ctx.stroke(_path)
}
game.sprites.background.drawShape = function (ctx, _piecesList, h, s, l, _lineWidth, _affinity) {
    let i = 0
    _piecesList.forEach((_piece) => {
        this.drawPiece(ctx, _piece, h, s+i%20, l+i%20, _lineWidth, _affinity)
        i+=4
       } 
    )
}

////////////////////////////////////////////////////////////////////////
// GEOMETRIC functions
////////////////////////////////////////////////////////////////////////
game.sprites.background.shapeToPath = function (_shape) {
    return _shape.map(_piece => {
        let _piecePath = new Path2D()
        _piece.forEach((_point, index) => {
            if (index === 0) {
                _piecePath.moveTo(_point[0], _point[1])
            } else {
                _piecePath.lineTo(_point[0], _point[1])
            }
        })
        _piecePath.closePath()
        return _piecePath
    })
}
game.sprites.background.triangulatePolygon = function(polygon) {
    // Function mostly generated by IA !
    if (!polygon || polygon.length < 3) return []
    let vertices = [...polygon]
    let triangles = []
    // 1. Determine winding order using the Shoelace formula
    let area = 0
    for (let i = 0; i < vertices.length; i++) {
        let j = (i + 1) % vertices.length
        area += vertices[i][0] * vertices[j][1] - vertices[j][0] * vertices[i][1]
    }
    // Invalid flat polygon
    if (area === 0) return [] 
    let isCCW = area > 0
    // 2. Ear clipping loop optimized to pick the best (most balanced) ear first
    let safetyLimit = vertices.length * 2
    while (vertices.length >= 3 && safetyLimit > 0) {
        safetyLimit--
        let bestEarIndex = -1
        let shortestDiagonal = Infinity
        // Scan all vertices to find the absolute best ear to cut
        for (let i = 0; i < vertices.length; i++) {
        let prevIdx = (i - 1 + vertices.length) % vertices.length
        let nextIdx = (i + 1) % vertices.length
        let prev = vertices[prevIdx]
        let curr = vertices[i]
        let next = vertices[nextIdx]
        // Convexity check via cross product
        let crossProduct = (curr[0] - prev[0]) * (next[1] - curr[1]) - (curr[1] - prev[1]) * (next[0] - curr[0])
        let isConvex = isCCW ? crossProduct > 0 : crossProduct < 0
        if (isConvex) {
            // Check if any other remaining vertex lies inside this candidate triangle
            let inside = false
            for (let j = 0; j < vertices.length; j++) {
            if (j === prevIdx || j === i || j === nextIdx) continue
            if (this.isPointInTriangle(vertices[j], prev, curr, next)) {
                inside = true
                break
            }
            }
            // If it's a valid ear, evaluate its diagonal length (distance between prev and next)
            if (!inside) {
            let diagLength = Math.hypot(next[0] - prev[0], next[1] - prev[1])
            // We look for the shortest diagonal to make the triangle as compact/equilateral as possible
            if (diagLength < shortestDiagonal) {
                shortestDiagonal = diagLength
                bestEarIndex = i
            }
            }
        }
        }
        // Cut the best ear found during this turn
        if (bestEarIndex !== -1) {
        let prevIdx = (bestEarIndex - 1 + vertices.length) % vertices.length
        let nextIdx = (bestEarIndex + 1) % vertices.length
        triangles.push([vertices[prevIdx], vertices[bestEarIndex], vertices[nextIdx]])
        vertices.splice(bestEarIndex, 1)
        } else {
        // Fallback if the polygon is self-intersecting or highly corrupted
        break
        }
    }
    return triangles
}
game.sprites.background.isPointInTriangle = function (p, a, b, c) {
    const sign = (p1, p2, p3) => {
        return (p1[0] - p3[0]) * (p2[1] - p3[1]) - (p2[0] - p3[0]) * (p1[1] - p3[1])
    }
    const d1 = sign(p, a, b)
    const d2 = sign(p, b, c)
    const d3 = sign(p, c, a)
    const hasNeg = (d1 < 0) || (d2 < 0) || (d3 < 0)
    const hasPos = (d1 > 0) || (d2 > 0) || (d3 > 0)
    return !(hasNeg && hasPos)
}
game.sprites.background.splitTriangle = function(_piece) {
    let [[Ax, Ay], [Bx, By], [Cx, Cy]] = _piece
    let maxL2 = this.maxLength ** 2
    // Length of each side
    let AB = (Bx - Ax) ** 2 + (By - Ay) ** 2
    let AC = (Cx - Ax) ** 2 + (Cy - Ay) ** 2
    let BC = (Cx - Bx) ** 2 + (Cy - By) ** 2
    // If small triangle do nothing
    if (AB <= maxL2 || AC <= maxL2 || BC <= maxL2) {
        return [_piece];
    }
    // Identify taller side and split accordingly
    if (AB >= AC && AB >= BC) {
        let P = [(2 * Bx + Ax) / 3, (2 * By + Ay) / 3]
        return [[P, _piece[1], _piece[2]], [P, _piece[2], _piece[0]]]
    } 
    if (AC >= AB && AC >= BC) {
        let P = [(2 * Cx + Ax) / 3, (2 * Cy + Ay) / 3]
        return [[P, _piece[0], _piece[1]], [P, _piece[2], _piece[1]]]
    } 
    let P = [(2 * Cx + Bx) / 3, (2 * Cy + By) / 3]
    return [[P, _piece[0], _piece[2]], [P, _piece[0], _piece[1]]]
}
game.sprites.background.splitShape = function(_shape) {
    let _newShape = []
    _shape.forEach((_piece) => {
        _newShape.push(...this.splitTriangle(_piece))
    } 
    )
    if(_newShape.length == _shape.length) {
        return _newShape
    } else {
        return game.sprites.background.splitShape (_newShape)
    }
}
game.sprites.background.createShapePaths = function(_shape) {
    // Step 1: triangulation 
    let _shapeTriangles = this.triangulatePolygon(_shape)
    // Step 2: split triangles
    return this.shapeToPath(this.splitShape(_shapeTriangles))
}

////////////////////////////////////////////////////////////////////////
// GRAPHICS
////////////////////////////////////////////////////////////////////////
game.sprites.background.initL1 = function() {
    this.L1 = {sky:[],tree:[],leaf:[],bkg:[],frg:[],rainb:[],egg:[],uni:[]}
    // SKY
    this.L1.sky.push(this.createShapePaths([[0,169],[188,335],[192,368],[104,357],[0,384]]))
    this.L1.sky.push(this.createShapePaths([[0,0],[0,74],[111,19],[283,44],[302,0]]))
    this.L1.sky.push(this.createShapePaths([[302,0],[283,44],[357,148],[297,269],[245,323],[255,376],[310,382],[387,366],[408,221],[574,146],[595,0]]))
    this.L1.sky.push(this.createShapePaths([[595,0],[574,145],[740,257],[773,405],[811,416],[941,333],[988,323],[966,242],[917,195],[835,170],[805,120],[909,0]]))
    this.L1.sky.push(this.createShapePaths([[909,0],[864,52],[998,43],[1062,97],[1002,228],[1022,316],[1089,301],[1158,320],[1098,249],[1112,139],[1280,47],[1280,0]]))
    this.L1.sky.push(this.createShapePaths([[525,355],[536,315],[569,298],[599,317],[620,365],[573,360],[564,316],[563,359]]))

    // TREES
    // Left tree
    this.L1.tree.push(this.createShapePaths([[205,469],[188,333],[119,204],[193,307],[219,266],[231,176],[204,134],[241,175],[277,161],[241,186],[232,267],[222,303],[245,322],[271,463]]))
    // Middle tree
    this.L1.tree.push(this.createShapePaths([[987,322],[965,241],[940,175],[894,114],[933,145],[955,122],[944,151],[1002,227],[1023,316]]))
    // Right tree
    this.L1.tree.push(this.createShapePaths([[1181,720],[1215,528],[1205,375],[1157,236],[1191,274],[1219,189],[1206,302],[1223,354],[1280,386],[1280,720]]))

    // LEAVES
    // Left tree
    this.L1.leaf.push(this.createShapePaths([[0,74],[113,19],[283,44],[357,148],[296,270],[245,322],[221,303],[232,269],[241,186],[277,161],[241,176],[204,135],[232,177],[219,267],[193,308],[119,204],[190,336],[0,168]]))
    // Middle tree
    this.L1.leaf.push(this.createShapePaths([[965,241],[916,194],[835,170],[805,118],[866,50],[997,43],[1062,97],[1002,228],[944,151],[955,122],[933,146],[893,113],[942,177]]))
    // Right tree
    this.L1.leaf.push(this.createShapePaths([[1205,377],[1098,249],[1112,139],[1280,48],[1280,386],[1223,355],[1206,302],[1221,181],[1191,276],[1155,233]]))

    // BACKGROUND
    this.L1.bkg.push(this.createShapePaths([[0,384],[104,357],[192,368],[205,470],[0,492]]))
    this.L1.bkg.push(this.createShapePaths([[255,375],[310,382],[473,350],[564,360],[564,418],[549,416],[519,445],[529,464],[519,498],[271,461]]))
    this.L1.bkg.push(this.createShapePaths([[573,360],[585,421],[620,426],[640,476],[631,472],[641,498],[875,462],[1212,485],[1205,376],[1156,319],[1091,301],[943,333],[811,416],[640,367]]))

    // FOREGROUND
    this.L1.frg.push(this.createShapePaths([[0,493],[271,462],[520,498],[511,529],[489,516],[496,613],[576,720],[0,719]]))
    this.L1.frg.push(this.createShapePaths([[544,675],[576,720],[854,720],[862,653],[786,653],[735,611],[769,616],[803,603],[787,475],[641,497],[654,529],[676,510],[678,608],[643,674]]))
    this.L1.frg.push(this.createShapePaths([[788,475],[804,604],[835,618],[884,606],[862,653],[855,720],[1182,720],[1215,527],[1212,485],[876,462]]))

    // RAINBOW
    this.L1.rainb.push(this.createShapePaths([[387,367],[409,362],[428,234],[569,170],[710,264],[748,398],[774,405],[740,257],[575,145],[407,221]]))
    this.L1.rainb.push(this.createShapePaths([[410,362],[428,234],[569,170],[710,264],[748,398],[728,393],[682,270],[567,194],[450,251],[431,358]]))
    this.L1.rainb.push(this.createShapePaths([[728,392],[705,386],[667,277],[568,217],[474,259],[452,354],[431,358],[450,251],[567,194],[682,270]]))
    this.L1.rainb.push(this.createShapePaths([[471,350],[452,354],[474,259],[567,218],[667,277],[705,386],[684,379],[643,286],[565,241],[486,282]]))
    this.L1.rainb.push(this.createShapePaths([[472,350],[487,282],[565,241],[643,286],[684,379],[664,374],[629,303],[566,261],[506,292],[490,353]]))
    this.L1.rainb.push(this.createShapePaths([[507,353],[491,352],[506,292],[566,261],[629,303],[664,374],[642,367],[617,311],[568,279],[519,304]]))
    this.L1.rainb.push(this.createShapePaths([[525,355],[507,353],[520,304],[568,279],[617,311],[642,367],[620,365],[599,317],[569,298],[536,315]]))

    // EGG
    this.L1.egg.push(this.createShapePaths([[489,515],[497,615],[544,675],[643,674],[678,608],[676,510],[638,543],[594,528],[544,552]]))
    this.L1.egg.push(this.createShapePaths([[736,611],[770,616],[803,603],[836,617],[884,606],[862,653],[786,653]]))

    // UNICORN
    this.L1.uni.push(this.createShapePaths([[526,540],[537,508],[559,506],[568,540],[544,552]]))
    this.L1.uni.push(this.createShapePaths([[607,533],[614,502],[633,503],[650,533],[638,544]]))
    this.L1.uni.push(this.createShapePaths([[640,476],[620,426],[585,421],[564,318],[564,418],[550,416],[519,445],[530,464],[588,483],[582,454]]))

    this.L1.uniWhite=this.createShapePaths([[526,540],[511,530],[529,464],[589,483],[582,455],[632,473],[654,528],[650,534],[633,503],[614,502],[607,533],[594,528],[568,540],[559,506],[536,508]])

}


game.sprites.background.drawL1 = function(ctx) {
    // SKY
    let h = 200
    let s = 60
    let l = 75     
    h = game.CONST.hColors.get('cyan')
    this.L1.sky.forEach((_shape) => {
        this.drawShape(ctx,_shape,h,s,l,this.lineWidth,'cyan')
    } 
    )    
    // LEVAVES
    h = game.CONST.hColors.get('gree')
    this.L1.leaf.forEach((_shape) => {
        this.drawShape(ctx,_shape,h,s,l,this.lineWidth,'gree')
    } 
    )    
    // TREE
    h = game.CONST.hColors.get('oran')
    this.L1.tree.forEach((_shape) => {
        this.drawShape(ctx,_shape,h,s,l,this.lineWidth,'oran')
    } 
    )    
    // BACKGROUND
    h = game.CONST.hColors.get('red')
    this.L1.bkg.forEach((_shape) => {
        this.drawShape(ctx,_shape,h,s,l,this.lineWidth,'red')
    } 
    )    
    // FOREGROUND
    h = game.CONST.hColors.get('yell')
    this.L1.frg.forEach((_shape) => {
        this.drawShape(ctx,_shape,h,s,l,this.lineWidth,'yell')
    } 
    )    
    // RAINBOW
    h = game.CONST.hColors.get('red')
    this.drawShape(ctx,this.L1.rainb[0],h,s,l,this.lineWidth,'red')
    h = game.CONST.hColors.get('oran')
    this.drawShape(ctx,this.L1.rainb[1],h,s,l,this.lineWidth,'oran')
    h = game.CONST.hColors.get('yell')
    this.drawShape(ctx,this.L1.rainb[2],h,s,l,this.lineWidth,'yell')
    h = game.CONST.hColors.get('gree')
    this.drawShape(ctx,this.L1.rainb[3],h,s,l,this.lineWidth,'gree')
    h = game.CONST.hColors.get('cyan')
    this.drawShape(ctx,this.L1.rainb[4],h,s,l,this.lineWidth,'cyan')
    h = game.CONST.hColors.get('blue')
    this.drawShape(ctx,this.L1.rainb[5],h,s,l,this.lineWidth,'blue')
    h = game.CONST.hColors.get('mage')
    this.drawShape(ctx,this.L1.rainb[6],h,s,l,this.lineWidth,'mage')
    // EGG
    h = game.CONST.hColors.get('mage')
    this.L1.egg.forEach((_shape) => {
        this.drawShape(ctx,_shape,h,s,l,this.lineWidth,'mage')
    } 
    )    
    // UNICORN
    h = game.CONST.hColors.get('blue')
    this.L1.uni.forEach((_shape) => {
        this.drawShape(ctx,_shape,h,s,l,this.lineWidth,'blue')
    } 
    )    
    h = game.CONST.hColors.get('blue')
    this.drawShape(ctx,this.L1.uniWhite,h,s,100,this.lineWidth,'blue')
    
}


game.sprites.background.drawFunction = function (ctx) {
    
    this.drawL1(ctx)

}

