game.sprites.background.init = function() {
    this.width = mge.game.width
    this.height = mge.game.height
    this.x = mge.game.width / 2
    this.y = mge.game.height / 2
    // Config
    this.maxLength  = 50
    this.lineWidth = 2
    this.isVisible = true
    // Create 2D paths
    this.initL1()
}

////////////////////////////////////////////////////////////////////////
// RENDER functions
////////////////////////////////////////////////////////////////////////
game.sprites.background.drawPiece = function (ctx, _path, h, s, l, _lineWidth, _affinity) {
    // Get the progress of the timer of the affinity
    let _timerProgress = game.timers[_affinity].progress
    // Calculate color depending of timer progress
    if (_timerProgress == 0) {
        // grey
        ctx.fillStyle = game.tools.hsla(0,0,90,100)
        ctx.strokeStyle = game.tools.hsla(0,0,50,100)
    } else if ((_timerProgress <= 0.2)) {
        ctx.fillStyle = game.tools.hsla(0,0,Math.min(100,80 + 200*_timerProgress),100)
        ctx.strokeStyle = game.tools.hsla(0,0,80,100)
    } else if ((_timerProgress <= 1)) {
        ctx.fillStyle = game.tools.hsla(h,s*_timerProgress,l+(100-l)*(1-_timerProgress),100)
        ctx.strokeStyle = game.tools.hsla(0,0,0,100)
    }
    // Draw
    ctx.lineWidth = _lineWidth
    ctx.lineJoin = 'round'
    ctx.fill(_path)
    ctx.stroke(_path)
}
game.sprites.background.drawShape = function (ctx, _piecesList, h, s, l, _lineWidth, _affinity) {
    let i = 0
    _piecesList.forEach((_piece) => {
        this.drawPiece(ctx, _piece, h, s+i%20, l+i%20, _lineWidth, _affinity)
        i+=4
       } 
    )
}

////////////////////////////////////////////////////////////////////////
// GEOMETRIC functions
////////////////////////////////////////////////////////////////////////
game.sprites.background.shapeToPath = function (_shape) {
    return _shape.map(_piece => {
        let _piecePath = new Path2D()
        _piece.forEach((_point, index) => {
            if (index === 0) {
                _piecePath.moveTo(_point[0], _point[1])
            } else {
                _piecePath.lineTo(_point[0], _point[1])
            }
        })
        _piecePath.closePath()
        return _piecePath
    })
}
game.sprites.background.triangulatePolygon = function(polygon) {
    // Function mostly generated by IA !
    if (!polygon || polygon.length < 3) return []
    let vertices = [...polygon]
    let triangles = []
    // 1. Determine winding order using the Shoelace formula
    let area = 0
    for (let i = 0; i < vertices.length; i++) {
        let j = (i + 1) % vertices.length
        area += vertices[i][0] * vertices[j][1] - vertices[j][0] * vertices[i][1]
    }
    // Invalid flat polygon
    if (area === 0) return [] 
    let isCCW = area > 0
    // 2. Ear clipping loop optimized to pick the best (most balanced) ear first
    let safetyLimit = vertices.length * 2
    while (vertices.length >= 3 && safetyLimit > 0) {
        safetyLimit--
        let bestEarIndex = -1
        let shortestDiagonal = Infinity
        // Scan all vertices to find the absolute best ear to cut
        for (let i = 0; i < vertices.length; i++) {
        let prevIdx = (i - 1 + vertices.length) % vertices.length
        let nextIdx = (i + 1) % vertices.length
        let prev = vertices[prevIdx]
        let curr = vertices[i]
        let next = vertices[nextIdx]
        // Convexity check via cross product
        let crossProduct = (curr[0] - prev[0]) * (next[1] - curr[1]) - (curr[1] - prev[1]) * (next[0] - curr[0])
        let isConvex = isCCW ? crossProduct > 0 : crossProduct < 0
        if (isConvex) {
            // Check if any other remaining vertex lies inside this candidate triangle
            let inside = false
            for (let j = 0; j < vertices.length; j++) {
            if (j === prevIdx || j === i || j === nextIdx) continue
            if (this.isPointInTriangle(vertices[j], prev, curr, next)) {
                inside = true
                break
            }
            }
            // If it's a valid ear, evaluate its diagonal length (distance between prev and next)
            if (!inside) {
            let diagLength = Math.hypot(next[0] - prev[0], next[1] - prev[1])
            // We look for the shortest diagonal to make the triangle as compact/equilateral as possible
            if (diagLength < shortestDiagonal) {
                shortestDiagonal = diagLength
                bestEarIndex = i
            }
            }
        }
        }
        // Cut the best ear found during this turn
        if (bestEarIndex !== -1) {
        let prevIdx = (bestEarIndex - 1 + vertices.length) % vertices.length
        let nextIdx = (bestEarIndex + 1) % vertices.length
        triangles.push([vertices[prevIdx], vertices[bestEarIndex], vertices[nextIdx]])
        vertices.splice(bestEarIndex, 1)
        } else {
        // Fallback if the polygon is self-intersecting or highly corrupted
        break
        }
    }
    return triangles
}
game.sprites.background.isPointInTriangle = function (p, a, b, c) {
    const sign = (p1, p2, p3) => {
        return (p1[0] - p3[0]) * (p2[1] - p3[1]) - (p2[0] - p3[0]) * (p1[1] - p3[1])
    }
    const d1 = sign(p, a, b)
    const d2 = sign(p, b, c)
    const d3 = sign(p, c, a)
    const hasNeg = (d1 < 0) || (d2 < 0) || (d3 < 0)
    const hasPos = (d1 > 0) || (d2 > 0) || (d3 > 0)
    return !(hasNeg && hasPos)
}
game.sprites.background.splitTriangle = function(_piece) {
    let [[Ax, Ay], [Bx, By], [Cx, Cy]] = _piece
    let maxL2 = this.maxLength ** 2
    // Length of each side
    let AB = (Bx - Ax) ** 2 + (By - Ay) ** 2
    let AC = (Cx - Ax) ** 2 + (Cy - Ay) ** 2
    let BC = (Cx - Bx) ** 2 + (Cy - By) ** 2
    // If small triangle do nothing
    if (AB <= maxL2 || AC <= maxL2 || BC <= maxL2) {
        return [_piece];
    }
    // Identify taller side and split accordingly
    if (AB >= AC && AB >= BC) {
        let P = [(2 * Bx + Ax) / 3, (2 * By + Ay) / 3]
        return [[P, _piece[1], _piece[2]], [P, _piece[2], _piece[0]]]
    } 
    if (AC >= AB && AC >= BC) {
        let P = [(2 * Cx + Ax) / 3, (2 * Cy + Ay) / 3]
        return [[P, _piece[0], _piece[1]], [P, _piece[2], _piece[1]]]
    } 
    let P = [(2 * Cx + Bx) / 3, (2 * Cy + By) / 3]
    return [[P, _piece[0], _piece[2]], [P, _piece[0], _piece[1]]]
}
game.sprites.background.splitShape = function(_shape) {
    let _newShape = []
    _shape.forEach((_piece) => {
        _newShape.push(...this.splitTriangle(_piece))
    } 
    )
    if(_newShape.length == _shape.length) {
        return _newShape
    } else {
        return game.sprites.background.splitShape (_newShape)
    }
}
game.sprites.background.createShapePaths = function(_shape) {
    // Step 1: triangulation 
    let _shapeTriangles = this.triangulatePolygon(_shape)
    // Step 2: split triangles
    return this.shapeToPath(this.splitShape(_shapeTriangles))
}

////////////////////////////////////////////////////////////////////////
// GRAPHICS
////////////////////////////////////////////////////////////////////////
game.sprites.background.initL1 = function() {
    this.L1 = {sky:[]}
    // SKY
    this.L1.sky.push(this.createShapePaths([[0,170],[188,335],[192,368],[104,357],[0,384]]))
    this.L1.sky.push(this.createShapePaths([[580,4],[1265,6],[1265,40],[1104,130],[1082,241],[1124,300],[1091,290],[1042,299],[1016,230],[1078,95],[1012,32],[862,35],[793,103],[812,171],[904,205],[954,241],[972,314],[937,320],[819,397],[788,395],[760,274],[588,144]]))
    this.L1.sky.push(this.createShapePaths([[-4,62],[124,5],[297,35],[370,145],[325,267],[266,324],[264,353],[308,364],[372,353],[380,221],[557,130],[562,7],[-4,-6]]))

}


game.sprites.background.drawL1 = function(ctx) {
    // SKY
    let h = 200
    let s = 65
    let l = 70     
    this.L1.sky.forEach((_shape) => {
        this.drawShape(ctx,_shape,h,s,l,this.lineWidth,'cyan')
    } 
    )    

    /*
    // SKY
    let h = 200
    let s = 65
    let l = 70     
    // TREE LEFT
    h = 30
    s = 30
    l = 60
    // LEAVES
    h = 115
    s = 50
    l = 50
    */ 
}


game.sprites.background.drawFunction = function (ctx) {
    
    this.drawL1(ctx)

}

